server:
 port: 8082
 
spring:
 profiles:
  active: local

---  
spring:
 config:
  activate:
   on-profile: local
 kafka:
  topic: "library-events"
#  producer:
#   bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
#   key-serializer: org.apache.kafka.common.serialization.StringSerializer
#   value-serializer: org.apache.kafka.common.serialization.StringSerializer 
#   properties:
#    retries: 10

 #admin:
  #properties:
   #bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
   
logging:
 level:
 # org:
  # springframework:
 #   web: DEBUG
  com: DEBUG
---
spring:
 config:
  activate:
   on-profile: non-prod
 kafka:
  producer:
   bootstrap-servers: non-prod:9092
   key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
   value-serializer: org.apache.kafka.common.serialization.StringSerializer   